name: Test Build OpenWrt

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      devices:
        description: '需要编译的固件类型'
        default: '["x86_64","cr660x"]'
      clean:
        description: 'clean ccache'
        default: 'false'

  push:
    branches:
      - main

env:
  REPO_URL: https://github.com/coolsnowwolf/lede
  REPO_BRANCH: master
  FEEDS_CONF: feeds.conf.default
  DIY_P1_SH: diy.sh
  DIY_P2_SH: diy-part2.sh
  UPLOAD_BIN_DIR: false
  UPLOAD_FIRMWARE: true
  UPLOAD_COWTRANSFER: false
  UPLOAD_WETRANSFER: true
  UPLOAD_RELEASE: true
  TZ: Asia/Shanghai

jobs:
  create-matrix:
    runs-on: ubuntu-latest
    name: Create Matrix
    steps:
      - name: Set Matrix
        id: set-matrix
        env:
          MATRIXS: ${{ github.event.inputs.devices }}
        run: |
          if [ -z $MATRIXS ]; then
            MATRIXS='["x86_64","cr660x"]'
          fi
          echo matrix=$MATRIXS
